version: "3.8"
services:
  web:
    build: ./app
    image: 305538495820.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_web
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8001
  nginx:
    build: ./nginx
    image: 305538495820.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:django_docker_aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8001:80
    depends_on:
      - web
volumes:
  static_volume:
